apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie
  labels:
    app: movie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
        - name: movie
          image: projectmovio/movie-service
          ports:
            - containerPort: 8082
          resources:
            requests:
              memory: "20Mi"
              cpu: "2m"
            limits:
              memory: "30Mi"
              cpu: "100m"
          env:
            - name: MOVIE_SERVICE_API_KEY
              value: ${MOVIE_SERVICE_API_KEY}