---
basePath: "/"
definitions:
  Movie:
    propeties:
      id:
        type: integer
      title:
        type: string
    type: object
  Movies:
    properties:
      page:
        type: integer
      results:
        type: array
        items:
          $ref: '#/definitions/Movie'

info:
  description: Serving routes for movie operations
  termsOfService: "/tos"
  title: Movio movie service api
  version: 0.0.1
  contact:
    responsibleOrganization: "Michal Sadowski"
    responsibleDeveloper: "Michal Sadowski"
    email: "michcio90po@gmail.com"
    url: "test"
swagger: '2.0'